" *** Plugins import
runtime plugins.vim

" *** Custom config
set nu " print the line number in front of each line
set ic " ignore case in search patterns
set hlsearch " highlight search matches
set backspace=2 " use backspace to delete

set expandtab " expand tab to spaces
set shiftwidth=4 " number of spaces to use for each step of (auto)indent.  Used for 'cindent', >>, <<, etc.
set softtabstop=4

" *** Plugins config
" ** Airline **
let g:airline_theme = 'solarized'
let g:airline_powerline_fonts = 1

" Always show bar, see https://github.com/vim-airline/vim-airline/issues/20 for details
set laststatus=2

" ** Colors solarized **
syntax enable
set background=dark
" colorscheme solarized

" ** vim-gitgutter
let g:gitgutter_map_keys = 0 "Remove all mappings, not used

" ** neocomplete
let g:neocomplete#enable_at_startup = 1

" ** autocompletion
filetype plugin indent on
filetype on
syntax on

" ** nerdcommenter
let mapleader=","
