" *** Plugins import
runtime plugins.vim

" *** Custom config

" *** Plugins config
" ** Airline **
let g:airline_theme = 'solarized'
let g:airline_powerline_fonts = 1

" Always show bar, see https://github.com/vim-airline/vim-airline/issues/20 for details
set laststatus=2

" ** Colors solarized **
syntax enable
set background=dark
colorscheme solarized
