"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
 $character\
"""

right_format = """
$cmd_duration\
$all\
$time"""

[time]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '[*${count} ](bold green)'
staged = '[+${count} ](bold yellow)'
modified = '[!${count} ](bold yellow)'
untracked = '[?${count}](bold blue)'
deleted = '[✘${count} ](bold red)'
format = '([$all_status$ahead_behind]($style))'

[character]
success_symbol = '[ ❯](bold green)'
error_symbol = '[ ❯](bold red)'

[git_branch]
truncation_length = 26

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 3

[java]
format = '[${symbol}(${version} )](red)'
symbol = ' '

[aws]
disabled = true

[gradle]
format = '[$symbol($version )]($style)'
symbol = ' '

[nodejs]
format = '[$symbol($version )]($style)'

[package]
format = '[$symbol($version )](208)'
symbol = ' '
