if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for script in $HOME/.scripts/*; do
  source $script
done

# Used to import private scripts stored in my bitbucket repository
if [[ -d "$HOME/.scripts.private" ]]; then
  for script in $HOME/.scripts.private/*; do
    source $script
  done
fi

# Configure iTerm2 tab titles based on current directory, example /Users/Albert/workspace/dotfiles -> ~/p/dotfiles
precmd () {
  window_title="\e]0;${${PWD/#"$HOME"/~}/workspace/w}\a"
  echo -ne "$window_title"
}

export PATH=.:~/bin:$PATH
export EDITOR="vim"

# If no GPG Suite https://help.github.com/articles/telling-git-about-your-gpg-key/
export GPG_TTY=$(tty)

export PLENV_ROOT=~/.plenv
export PLENV_SHELL=zsh
PLENV_VERSION=$(<$PLENV_ROOT/version)
export PATH="$PLENV_ROOT/shims:$PLENV_ROOT/versions/$PLENV_VERSION/bin:$PATH"

# tabtab source for serverless package, automatically added by serverless yarn package
# uninstall by removing these lines or running `tabtab uninstall serverless`
YARN_TABTAB="$HOME/.config/yarn/global/node_modules/tabtab"
[[ -f $YARN_TABTAB/.completions/serverless.zsh ]] && . $YARN_TABTAB/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f $YARN_TABTAB/.completions/sls.zsh ]] && . $YARN_TABTAB/.completions/sls.zsh

# Adding colors to more & less commands, cat is also colored with an alias
export MORE='-R'
export LESSOPEN='|pygmentize %s'

eval "$(jenv init -)"
