if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for script in $HOME/.scripts/*; do
  source $script
done

# Used to import private scripts stored in my bitbucket repository
if [[ -d "$HOME/.scripts.private" ]]; then
  for script in $HOME/.scripts.private/*; do
    source $script
  done
fi

export PATH=.:~/bin:~/.local/bin:$PATH
export EDITOR="vim"

# If no GPG Suite https://help.github.com/articles/telling-git-about-your-gpg-key/
export GPG_TTY=$(tty)

# Adding colors to more & less commands, cat is also colored with an alias
export MORE='-R'
export LESSOPEN='|pygmentize %s'
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

# Directory where brew command installs nvm
export NVM_DIR="/usr/local/opt/nvm"

# Configure iTerm2 tab titles based on current directory, example /Users/Albert/workspace/dotfiles -> ~/p/dotfiles
precmd () {
  window_title="\e]0;${${PWD/#"$HOME"/~}/workspace/w}\a"
  echo -ne "$window_title"
}

if [[ -d ~/.plenv ]]; then
  export PLENV_ROOT=~/.plenv
  export PLENV_SHELL=zsh
  PLENV_VERSION=$(<$PLENV_ROOT/version)
  export PATH="$PLENV_ROOT/shims:$PLENV_ROOT/versions/$PLENV_VERSION/bin:$PATH"
fi

# To enable shims and autocompletion add to your profile:
# if which jenv > /dev/null; then eval "$(jenv init - --no-rehash)"; fi

# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init - --no-rehash)"
# fi

# https://www.iterm2.com/documentation-shell-integration.html
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

load-nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
}

load-nvmrc() {
  [[ -a .nvmrc ]] || return

  if [[ -f .nvmrc && -r .nvmrc ]]; then
    if ! type nvm >/dev/null; then
      load-nvm
    fi
    nvm use
  fi
}

check-local-java() {
  [[ -a .java-version ]] || return

  if [[ -f .java-version && -r .java-version ]]; then
    command printf "Now using local version of java: $(cat .java-version)\n"
  fi
}

# Automatically call nvm use if the folder has a .nvmrc file
autoload -U add-zsh-hook
add-zsh-hook chpwd load-nvmrc
add-zsh-hook chpwd check-local-java

# load bashcompinit for some old bash completions
#autoload -U +X bashcompinit && bashcompinit
